/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoLabRouteImport } from './routes/logo-lab'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSystemHealthRouteImport } from './routes/api/system.health'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiFounderSessionRouteImport } from './routes/api/founder.session'
import { Route as ApiFounderGithubLoginRouteImport } from './routes/api/founder.github-login'
import { Route as AuthenticatedSettingsDomainsRouteImport } from './routes/_authenticated/settings.domains'
import { Route as ApiAgentsDiffDecisionRouteImport } from './routes/api/agents.diff.decision'
import { Route as ApiAgentsSlugChatRouteImport } from './routes/api/agents.$slug.chat'

const LogoLabRoute = LogoLabRouteImport.update({
  id: '/logo-lab',
  path: '/logo-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemHealthRoute = ApiSystemHealthRouteImport.update({
  id: '/api/system/health',
  path: '/api/system/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFounderSessionRoute = ApiFounderSessionRouteImport.update({
  id: '/api/founder/session',
  path: '/api/founder/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFounderGithubLoginRoute = ApiFounderGithubLoginRouteImport.update({
  id: '/api/founder/github-login',
  path: '/api/founder/github-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsDomainsRoute =
  AuthenticatedSettingsDomainsRouteImport.update({
    id: '/settings/domains',
    path: '/settings/domains',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAgentsDiffDecisionRoute = ApiAgentsDiffDecisionRouteImport.update({
  id: '/api/agents/diff/decision',
  path: '/api/agents/diff/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsSlugChatRoute = ApiAgentsSlugChatRouteImport.update({
  id: '/api/agents/$slug/chat',
  path: '/api/agents/$slug/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/health': typeof HealthRoute
  '/logo-lab': typeof LogoLabRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/domains': typeof AuthenticatedSettingsDomainsRoute
  '/api/founder/github-login': typeof ApiFounderGithubLoginRoute
  '/api/founder/session': typeof ApiFounderSessionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/agents/$slug/chat': typeof ApiAgentsSlugChatRoute
  '/api/agents/diff/decision': typeof ApiAgentsDiffDecisionRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/health': typeof HealthRoute
  '/logo-lab': typeof LogoLabRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/domains': typeof AuthenticatedSettingsDomainsRoute
  '/api/founder/github-login': typeof ApiFounderGithubLoginRoute
  '/api/founder/session': typeof ApiFounderSessionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/agents/$slug/chat': typeof ApiAgentsSlugChatRoute
  '/api/agents/diff/decision': typeof ApiAgentsDiffDecisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/health': typeof HealthRoute
  '/logo-lab': typeof LogoLabRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/domains': typeof AuthenticatedSettingsDomainsRoute
  '/api/founder/github-login': typeof ApiFounderGithubLoginRoute
  '/api/founder/session': typeof ApiFounderSessionRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/system/health': typeof ApiSystemHealthRoute
  '/api/agents/$slug/chat': typeof ApiAgentsSlugChatRoute
  '/api/agents/diff/decision': typeof ApiAgentsDiffDecisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/health'
    | '/logo-lab'
    | '/api/health'
    | '/auth/callback'
    | '/settings/domains'
    | '/api/founder/github-login'
    | '/api/founder/session'
    | '/api/public/health'
    | '/api/system/health'
    | '/api/agents/$slug/chat'
    | '/api/agents/diff/decision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/health'
    | '/logo-lab'
    | '/api/health'
    | '/auth/callback'
    | '/'
    | '/settings/domains'
    | '/api/founder/github-login'
    | '/api/founder/session'
    | '/api/public/health'
    | '/api/system/health'
    | '/api/agents/$slug/chat'
    | '/api/agents/diff/decision'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/health'
    | '/logo-lab'
    | '/api/health'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/settings/domains'
    | '/api/founder/github-login'
    | '/api/founder/session'
    | '/api/public/health'
    | '/api/system/health'
    | '/api/agents/$slug/chat'
    | '/api/agents/diff/decision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  HealthRoute: typeof HealthRoute
  LogoLabRoute: typeof LogoLabRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiFounderGithubLoginRoute: typeof ApiFounderGithubLoginRoute
  ApiFounderSessionRoute: typeof ApiFounderSessionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiSystemHealthRoute: typeof ApiSystemHealthRoute
  ApiAgentsSlugChatRoute: typeof ApiAgentsSlugChatRoute
  ApiAgentsDiffDecisionRoute: typeof ApiAgentsDiffDecisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logo-lab': {
      id: '/logo-lab'
      path: '/logo-lab'
      fullPath: '/logo-lab'
      preLoaderRoute: typeof LogoLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/health': {
      id: '/api/system/health'
      path: '/api/system/health'
      fullPath: '/api/system/health'
      preLoaderRoute: typeof ApiSystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founder/session': {
      id: '/api/founder/session'
      path: '/api/founder/session'
      fullPath: '/api/founder/session'
      preLoaderRoute: typeof ApiFounderSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/founder/github-login': {
      id: '/api/founder/github-login'
      path: '/api/founder/github-login'
      fullPath: '/api/founder/github-login'
      preLoaderRoute: typeof ApiFounderGithubLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/domains': {
      id: '/_authenticated/settings/domains'
      path: '/settings/domains'
      fullPath: '/settings/domains'
      preLoaderRoute: typeof AuthenticatedSettingsDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agents/diff/decision': {
      id: '/api/agents/diff/decision'
      path: '/api/agents/diff/decision'
      fullPath: '/api/agents/diff/decision'
      preLoaderRoute: typeof ApiAgentsDiffDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$slug/chat': {
      id: '/api/agents/$slug/chat'
      path: '/api/agents/$slug/chat'
      fullPath: '/api/agents/$slug/chat'
      preLoaderRoute: typeof ApiAgentsSlugChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsDomainsRoute: typeof AuthenticatedSettingsDomainsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsDomainsRoute: AuthenticatedSettingsDomainsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  HealthRoute: HealthRoute,
  LogoLabRoute: LogoLabRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiFounderGithubLoginRoute: ApiFounderGithubLoginRoute,
  ApiFounderSessionRoute: ApiFounderSessionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiSystemHealthRoute: ApiSystemHealthRoute,
  ApiAgentsSlugChatRoute: ApiAgentsSlugChatRoute,
  ApiAgentsDiffDecisionRoute: ApiAgentsDiffDecisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
